version: 2.1

jobs:
  testing:
    docker:
      - image: cimg/go:1.17
        auth:
          username: ebiy0rom0
          password: $DOCKERHUB_PASS
    working_directory: ~/go/src/github.com/ebiy0rom0/sekareco_srv
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: integration test
          command: make test INTEGRATE=1

workflows:
  build-workflow:
    jobs:
      - testing:
          context:
            - secret