version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    working_directory: /go/src/github.com/ebiy0rom0/sekareco_srv
    steps:
      - checkout
      - run:
          name: unit test
          command: go test -v ./...
