basePath: /api/v1
consumes:
- application/json
host: localhost:8000
info:
  contact: {}
  description: sekareco REST API server.
  license:
    name: MIT License
    url: https://github.com/ebiy0rom0/sekareco_srv/blob/develop/LICENSE
  title: sekareco_srv
  version: 1.0.0-beta
paths:
  /musics:
    get:
      consumes:
      - application/json
      description: get all music master records
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "503":
          description: Service Unavailable
      summary: wip
      tags:
      - musics
  /prsk/persons/{personID}:
    put:
      consumes:
      - application/json
      description: person account status change
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: wip
      tags:
      - persons
  /signup:
    post:
      consumes:
      - application/json
      description: wip
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "503":
          description: Service Unavailable
      summary: wip
      tags:
      - accounts
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
