name: Unit-Test

on:
  push:
    branches: [ "develop" ]
  schedule:
  - cron: '0 19 * * 0'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.x

    - name: Test
      run: make test
